name: 'Configuration Manager'
type: module
description: 'Allows administrators to import and export configuration changes.'
package: Core
# version: VERSION
configure: config.sync

# Information added by Drupal.org packaging script on 2021-10-06
version: '9.2.7'
project: 'drupal'
datestamp: 1633544335
