name: Testing site config
type: profile
description: 'Minimal profile for testing with default site config.'
# version: VERSION
hidden: true

# Information added by Drupal.org packaging script on 2021-10-06
version: '9.2.7'
project: 'drupal'
datestamp: 1633544335
